package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatCuisine;


import java.util.List;

public interface EatCuisineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 刘洋
     * @desc 管理员删除菜品信息
     * @date 2020/2/24
     */
    int deleteByPrimaryKey(Integer cuisineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 刘洋
     * @desc 增加菜品信息
     * @date 2020/2/23
     */
    int insertSelective(EatCuisine eatCuisine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatCuisine selectByPrimaryKey(Integer cuisineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 刘洋
     * @desc 管理员修改菜品信息
     * @date 2020/2/24
     */
    int updateByPrimaryKeySelective(EatCuisine eatCuisine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatCuisine record);

    /**
     * @author 刘洋
     * @desc 查询菜品信息
     * @date 2020/2/23
     */
    public List<EatCuisine> getCuisineList();

    /**
     * @author 刘洋
     * @desc 根据id查询菜品信息
     * @date 2020/2/23
     */
    public EatCuisine getCuisineById(String CUISINE_ID);


}