package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatSecurity;
import cn.kgc.eat.pojo.EatUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatSecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author
     * @des删除商家食品安全档案
     * @date 2020/2/25
     */
    int deleteByPrimaryKey(Integer securityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author
     * @des增加商家食品安全档案
     * @date 2020/2/25
     */
    int insertSelective(EatSecurity eatSecurity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatSecurity selectByPrimaryKey(Integer securityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author
     * @des修改商家食品安全档案
     * @date 2020/2/25
     */
    int updateByPrimaryKeySelective(EatSecurity eatSecurity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_security
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatSecurity record);
    /**
     * @author
     * @desc 查询
     * @date 2020/2/25
     */
    public List<EatSecurity> getList();
    /**
     * @author
     * @desc 根据id查询
     * @date 2020/2/25
     */
    public EatSecurity getSecurityById(@Param("SECURITY_ID") String SECURITY_ID );
}